//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Urun()
        {
            this.Tbl_UrunHareket = new HashSet<Tbl_UrunHareket>();
            this.Tbl_UrunKabul = new HashSet<Tbl_UrunKabul>();
            this.Tbl_UrunTakip = new HashSet<Tbl_UrunTakip>();
        }
    
        public int Urun_id { get; set; }
        public string Ad { get; set; }
        public string Marka { get; set; }
        public Nullable<decimal> Alısfiyat { get; set; }
        public Nullable<decimal> Satisfiyat { get; set; }
        public Nullable<short> Stok { get; set; }
        public Nullable<short> Kategori { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Tbl_Kategori Tbl_Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UrunHareket> Tbl_UrunHareket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UrunKabul> Tbl_UrunKabul { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UrunTakip> Tbl_UrunTakip { get; set; }
    }
}
